Agregado del operador para osciloscopios 'medir_RC' para medir capacitancias
pablodecesare1/instrumentacion_virtual pull request #10
Opened 2023-08-22 05:48 UTC by brunogle

Enviado como Trabajo Practico 3 de Bruno Glecer, Uriel Sandomir y Jonathan Yujra.

Este fork agrega principalmente el operador "medir_RC" en la clase "Operador_osciloscopio" e implementa los métodos: FFT, Potencia, Lissajous, Tiempo.

Tambien estandariza la indentación mixta que algunos archivos tenian a 4 espacios en lugar de tabulaciones.

2023-08-22 05:49 UTC, brunogle commented on InstVirtualLib/analizador_espectro.py
Solo cambios en tabulaciones

2023-09-08 12:51 UTC, RawthiL requested changes
Muy bueno, le faltan ventanas a las FFt y un script que aplique el proceso completo (un .py que podamos ejecutar cuando tengamos todo conectado)

2023-09-08 12:51 UTC, RawthiL commented on InstVirtualLib/mediciones.py
> +        frec_vg, mag_vg, fase_vg = self.fft_componente_principal(t,vg)
Falta aplicar ventanas antes de fft.

2023-09-08 12:51 UTC, RawthiL commented on InstVirtualLib/mediciones.py
> +        vg_filt = savgol_filter(vg, round(0.5/(periodo_sampleo*frecuencia)), 4)
Este filtrado deberia ser opcional y desactivado por default. No deberia hacer falta. Esto modifica los cruces por cero de la señal

2023-09-08 12:51 UTC, RawthiL commented on InstVirtualLib/operador.py
> +        debe aplicar una señal senoida. La frecuencia exacta no es importante, pero debe
senoida (typo)

2023-09-08 12:51 UTC, RawthiL commented on InstVirtualLib/operador.py
> +        se encuentre trigereando la señal correctamente.
El trigger no importa mucho ya que cuando se le pide trazo al osciloscopio no da lo mismo que hacer un single trigger. Es decir, si el trigger captura en algun punto la señal, entonces lo vamos a ver correctamente, no improta si la pantalla del osciloscopio tiene jitter.

2023-09-08 12:51 UTC, RawthiL commented on InstVirtualLib/operador.py
> +        C = 0
no hace falta esto aca, si no pueden obtener c va a tirar error

2023-09-10 00:16 UTC, brunogle commented
Ahí corregí los errores y agregue el script para probar medir_RC

2023-10-06 12:25 UTC, RawthiL approved these changes
TP OK

2023-10-06 12:39 UTC, merged