agrego metodos de medicion para el RC
pablodecesare1/instrumentacion_virtual pull request #9
Opened 2023-07-14 18:45 UTC by spalozzo

2023-08-20 14:12 UTC, RawthiL requested changes

2023-08-20 14:12 UTC, RawthiL commented on InstVirtualLib/mediciones.py
> +    def alt_Vmed(self, tiempo, tension):
Esta funcion tiene la misma descripcion que "Vmed" pero no hace lo que dice la descripcion y además no se utiliza en ningún lado. Remover.

2023-08-20 14:12 UTC, RawthiL commented on InstVirtualLib/mediciones.py
> +        fft = np.abs(np.fft.fft(tension))
Estan haciendo dos veces el calculo de la fft, acá y en la linea 104. Haganlo una sola vez y obtengan el modulo y la fase del mismo calculo de fft.

2023-08-20 14:12 UTC, RawthiL commented on InstVirtualLib/mediciones.py
> +        fft = np.abs(np.fft.fft(tension))
Además, modifiquen el nombre de la variable "fft" no me indica q en realidad es el modulo de la fft.

2023-08-20 14:12 UTC, RawthiL commented on InstVirtualLib/mediciones.py
> +        frec = fcia[posicion_max_fft[0]][0] # Frecuencia del pico (de la senoidal)
"fcia" es un vector, al cual le buscan la posicion del maximo, hasta ahi bien. ¿que es el segundo "[0]"? ¿porque lo aplican?

2023-08-20 14:12 UTC, RawthiL commented on InstVirtualLib/mediciones.py
> +    def get_zeros_signal(self, signal_in, delta_min = 5):
Agregar descripcion de la función

2023-08-20 14:12 UTC, RawthiL commented on InstVirtualLib/mediciones.py
> +    def mod_y_fase_comp_principal_fft(self, tiempo, tension):
Agregar comentario sobre el uso de la función en su descripccion.

2023-08-20 14:12 UTC, RawthiL commented on InstVirtualLib/mediciones.py
> +    def calculo_rc_FFT(self, valor_r, tiempo, tension_gen, tension_r):
Agregar descripcion de función

2023-08-20 14:12 UTC, RawthiL commented on InstVirtualLib/mediciones.py
> +    def calculo_rc_potencia(self, valor_r, tiempo, tension_gen, tension_r):
Agregar descripccion funcion.

2023-08-20 14:12 UTC, RawthiL commented on InstVirtualLib/mediciones.py
> +    def calculo_rc_lissajous(self, valor_r, tiempo, tension_gen, tension_r):
Agregar descripcion de funcion

2023-08-20 14:12 UTC, RawthiL commented on InstVirtualLib/mediciones.py
> +        tension_gen = tension_gen - np.average(tension_gen)
Hay funciones para calcular el valor medio. Usen esas, no repitan "np.average"

2023-08-20 14:12 UTC, RawthiL commented on InstVirtualLib/mediciones.py
> +        #print(f"Ciclos completos: {ciclos}")
Remover codigo de debug o dejarlo disponible bajo un flag "VERBOSE", q sea un parametro opcional de la funcion.

2023-08-20 14:12 UTC, RawthiL commented on InstVirtualLib/mediciones.py
> +    def calculo_rc_temporal(self, valor_r, tiempo, tension_gen, tension_r):
Agegar descripcion de la funcion

2023-08-20 14:12 UTC, RawthiL commented on InstVirtualLib/mediciones.py
> +        for i in range(0, 4000): # Recorro todo el csv
ese 4000 hardcodeado no puede existir ahi.
Además la funcion no esta hecha para csvs

2023-08-20 14:12 UTC, RawthiL commented on InstVirtualLib/mediciones.py
> +        delta_t = time1 - time2 # Delta t entre ceros de la senoidal
Tienen una funcion que busca cruces por cero, usen esa y borren este metodo que malisimo. Si anda es casualidad.

2023-08-20 14:12 UTC, RawthiL commented on InstVirtualLib/mediciones.py
> +        fft_data= self.mod_y_fase_comp_principal_fft(tiempo, tension_gen)
No usen FFT para este metodo, encuentren la frecuencia de la señal con los cruces por cero.

2023-09-08 12:53 UTC, RawthiL commented
Correcciones muchahos?

2023-09-26 20:55 UTC, spalozzo commented
Buenas, ya hicimos un pull request con los cambios indicados. Se nos
complicó para probarlo con los equipos pero ya verificamos que funcione
todo bien.

Nos vemos el viernes, abrazo!

El vie, 8 sept 2023 a las 9:53, Ramiro R. C. ***@***.***>)
escribió:

> Correcciones muchahos?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/pablodecesare1/instrumentacion_virtual/pull/9#issuecomment-1711624154>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AYPULSTWA7O4KMGUQ77VSP3XZMIMHANCNFSM6AAAAAA2KVQNV4>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-10-06 12:38 UTC, RawthiL approved these changes
TP OK.

No va a merge pq hicieron mal el merge de generadores arbitrarios a su fork, borrando todo el generador nuevo.

2023-10-06 12:38 UTC, closed without merging